/*
 * Copyright 2014 Davy Maddelein.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.compomics.pepshell.view.components;

import com.compomics.pepshell.view.PossibleMetaDataAnnotationsEnum;
import java.awt.Component;
import java.awt.event.ItemEvent;

import javax.swing.*;
import javax.swing.text.*;

/**
 * @author Davy Maddelein
 */
public class MetaDataRowPanel extends javax.swing.JPanel {

    private JComboBox booleanbox = new JComboBox(new String[]{"true", "false"});

    /**
     * Creates new form MetaDataRowPanel
     */
    public MetaDataRowPanel() {
        initComponents();
        booleanbox.setMaximumSize(new java.awt.Dimension(100, 20));
        booleanbox.setMinimumSize(new java.awt.Dimension(100, 20));
        booleanbox.setPreferredSize(new java.awt.Dimension(100, 20));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        annotationComboBox = new javax.swing.JComboBox<>(com.compomics.pepshell.view.PossibleMetaDataAnnotationsEnum.values());
        annotationTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(350, 50));
        setMinimumSize(new java.awt.Dimension(350, 50));
        setPreferredSize(new java.awt.Dimension(350, 50));

        annotationComboBox.setMaximumSize(new java.awt.Dimension(100, 20));
        annotationComboBox.setMinimumSize(new java.awt.Dimension(100, 20));
        annotationComboBox.setPreferredSize(new java.awt.Dimension(100, 20));
        annotationComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                annotationComboBoxItemStateChanged(evt);
            }
        });

        annotationTextField.setMaximumSize(new java.awt.Dimension(100, 20));
        annotationTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        annotationTextField.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(annotationComboBox, 0, 120, Short.MAX_VALUE)
                .addGap(73, 73, 73)
                .addComponent(annotationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annotationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annotationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void annotationComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_annotationComboBoxItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (((PossibleMetaDataAnnotationsEnum) annotationComboBox.getSelectedItem() == PossibleMetaDataAnnotationsEnum.HASHEADERS)) {
                ((GroupLayout) this.getLayout()).replace(annotationTextField, booleanbox);
            } else {
                if (booleanbox.isShowing()) {
                    ((GroupLayout) this.getLayout()).replace(booleanbox, annotationTextField);
                }
                ((PlainDocument) annotationTextField.getDocument()).setDocumentFilter(((PossibleMetaDataAnnotationsEnum) annotationComboBox.getSelectedItem()).getFilter());
            }
        }
    }//GEN-LAST:event_annotationComboBoxItemStateChanged

    public Component getComponent() {
        if (annotationTextField.isVisible()) {
            return annotationTextField;
        } else {
            return booleanbox;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<com.compomics.pepshell.view.PossibleMetaDataAnnotationsEnum> annotationComboBox;
    private javax.swing.JTextField annotationTextField;
    // End of variables declaration//GEN-END:variables

    public JComboBox<PossibleMetaDataAnnotationsEnum> getComboBox() {
        return annotationComboBox;
    }

    public String getText() {
        if (annotationTextField.isVisible()) {
            return annotationTextField.getText();
        } else {
            return (String) booleanbox.getSelectedItem();
        }
    }
}
