package com.compomics.pepshell.view.panels;

import com.compomics.pepshell.model.ProteinInterface;
import com.compomics.pepshell.view.DrawModes.DrawModeUtilities;
import java.awt.Component;
import java.awt.Dimension;

/**
 *
 * @author Niels Hulstaert
 */
class ExperimentAggregatorPanel extends javax.swing.JPanel {

    private ProteinInterface referenceProtein;

    /**
     * Creates new form ExperimentAggregatorPanel
     */
    public ExperimentAggregatorPanel() {
        initComponents();
    }

    public void setReferenceProtein(ProteinInterface referenceProtein) {
        this.referenceProtein = referenceProtein;
    }

    @Override
    public Dimension getPreferredSize() {
        if (referenceProtein != null) {
            int height = 0;
            for (Component component : this.getComponents()) {
                height += component.getPreferredSize().height;
            }
            return new Dimension(DrawModeUtilities.getInstance().scale(referenceProtein.getProteinSequence().length()) + 150, height);
        } else {
            return super.getPreferredSize();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
