
package com.compomics.pepshell.view.panels;

import com.compomics.pepshell.ProgramVariables;
import com.compomics.pepshell.model.Protein;
import java.awt.Dimension;

/**
 *
 * @author Niels Hulstaert
 */
public class ExperimentsPanel extends javax.swing.JPanel {

    private Protein referenceProtein;
    
    /**
     * Creates new form ExperimentsPanel
     */
    public ExperimentsPanel() {
        initComponents();                
    }

    public void setReferenceProtein(Protein referenceProtein) {
        this.referenceProtein = referenceProtein;
    }

        @Override
    public Dimension getPreferredSize() {
        if (referenceProtein != null) {
            return new Dimension((int) Math.ceil(referenceProtein.getProteinSequence().length() * ProgramVariables.SCALE) + 150, this.getHeight());
        } else {
            return super.getPreferredSize();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
