/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.pepshell.view.panels;

import com.compomics.pepshell.view.components.MetaDataComboBox;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTextField;

/**
 *
 * @author svend
 */
public class ExtraMetaDataAnnotatorPanel extends javax.swing.JPanel {

    private Map<String, Integer> metaDataAnnotations = new HashMap<>();

    /**
     * Creates new form ExtraMetaDataAnnotatorPanel
     */
    public ExtraMetaDataAnnotatorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        metaDataComboBox1 = new com.compomics.pepshell.view.components.MetaDataComboBox();
        possibleMetaDataLabel = new javax.swing.JLabel();
        addRowButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jTextField1.setPreferredSize(new java.awt.Dimension(35, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 14);
        add(jTextField1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(metaDataComboBox1, gridBagConstraints);

        possibleMetaDataLabel.setText("possible meta data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        add(possibleMetaDataLabel, gridBagConstraints);

        addRowButton.setText("add another row");
        addRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRowButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(addRowButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void addRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowButtonActionPerformed
        //lower the button
        GridBagConstraints constraints = ((GridBagLayout) this.getLayout()).getConstraints(addRowButton);
        constraints.gridy++;
        ((GridBagLayout) this.getLayout()).setConstraints(addRowButton, constraints);
        //add the combobox
        constraints.gridy = constraints.gridy - 2;
        constraints.gridx = 0;
        this.add(new MetaDataComboBox(), constraints);
        //add the text field
        constraints.gridx = 1;
        this.add(new JTextField(), constraints);
    }//GEN-LAST:event_addRowButtonActionPerformed

    public Map<String, Integer> getMetaDataAnnotations() {
        return Collections.unmodifiableMap(metaDataAnnotations);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRowButton;
    private javax.swing.JTextField jTextField1;
    private com.compomics.pepshell.view.components.MetaDataComboBox metaDataComboBox1;
    private javax.swing.JLabel possibleMetaDataLabel;
    // End of variables declaration//GEN-END:variables
}
