package com.compomics.pepshell.view.panels;

import com.compomics.pepshell.model.Protein;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Davy
 */
public class PreloadProteinFilterPanel extends javax.swing.JPanel {

    /**
     * Creates new form PreloadProteinFilterPanel
     */
    //probably replace the accession text area with a list with add and remove buttons
    public PreloadProteinFilterPanel() {
        initComponents();
    }

    public List<Protein> getProteinsToFilterWith() {
        List<Protein> filterList = new ArrayList<Protein>();
        if (!accessionTextArea.getText().isEmpty()) {
            for (String accession : Arrays.asList(accessionTextArea.getText().split("\n"))) {
                filterList.add(new Protein(accession));
            }
        }
        return filterList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accessionScrollPane = new javax.swing.JScrollPane();
        accessionTextArea = new javax.swing.JTextArea();
        filterCheckbox = new javax.swing.JCheckBox();
        importSubsetButton = new javax.swing.JButton();
        saveSubsetButton = new javax.swing.JButton();

        accessionTextArea.setColumns(20);
        accessionTextArea.setRows(5);
        accessionTextArea.setText("list of accessions separated by enters");
        accessionScrollPane.setViewportView(accessionTextArea);

        filterCheckbox.setText("remove this subset instead");

        importSubsetButton.setText("import subset ...");

        saveSubsetButton.setText("save subset...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(accessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterCheckbox)
                    .addComponent(importSubsetButton)
                    .addComponent(saveSubsetButton))
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filterCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(importSubsetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveSubsetButton))
                    .addComponent(accessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane accessionScrollPane;
    private javax.swing.JTextArea accessionTextArea;
    private javax.swing.JCheckBox filterCheckbox;
    private javax.swing.JButton importSubsetButton;
    private javax.swing.JButton saveSubsetButton;
    // End of variables declaration//GEN-END:variables
}
