package com.compomics.pepshell.view.frames;

import com.compomics.pepshell.DataModeController;
import com.compomics.pepshell.FaultBarrier;
import com.compomics.pepshell.controllers.DAO.DbDAO;
import com.compomics.pepshell.controllers.DataModes.FastaDataMode;
import com.compomics.pepshell.controllers.properties.ViewProperties;
import com.compomics.pepshell.model.AnalysisGroup;
import com.compomics.pepshell.model.Experiment;
import com.compomics.pepshell.model.Property;
import com.compomics.pepshell.model.Protein;
import com.compomics.pepshell.model.enums.ViewPropertyEnum;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Davy
 */
public class ProjectSelectionTreeFrame extends javax.swing.JFrame implements Observer {

    private List<Experiment> selectedProjectsList = new ArrayList<Experiment>();
    private FaultBarrier faultBarrier = FaultBarrier.getInstance();
    private Experiment referenceProject;
    private File fastaFile;

    /**
     * Creates new form ProjectSelectionTreeFrame all this is pretty much unsafe
     * when doing reflection
     */
    public ProjectSelectionTreeFrame() {
        initComponents();
        filterPanel.setVisible(false);
        this.setVisible(true);
        try {
            fillProjectList();
        } catch (Exception ex) {
            faultBarrier.handleException(ex);
            JOptionPane.showMessageDialog(null, "something went wrong while retrieving the list of projects:\n" + ex.getMessage());
        }
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        projectList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        referenceProjectTextBox = new javax.swing.JTextArea();
        addReferenceProjectButton = new javax.swing.JButton();
        removeReferenceProjectButton = new javax.swing.JButton();
        toProjectTreeButton = new javax.swing.JButton();
        addAnalysisGroupButton = new javax.swing.JButton();
        removeAnalysisGroupButton = new javax.swing.JButton();
        removeProjectButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        projectTree = new com.compomics.pepshell.view.components.DragAndDropTree();
        analyseButton = new javax.swing.JButton();
        fastaLocationTextField = new javax.swing.JTextField();
        addFastaButton = new javax.swing.JButton();
        ownFastaCheckBox = new javax.swing.JCheckBox();
        filterSubsetCheckBox = new javax.swing.JCheckBox();
        filterPanel = new javax.swing.JPanel();
        accessionScrollPane = new javax.swing.JScrollPane();
        accessionTextArea = new javax.swing.JTextArea();
        filterCheckbox = new javax.swing.JCheckBox();
        importSubsetButton = new javax.swing.JButton();
        saveSubsetButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("project selection");

        jScrollPane1.setViewportView(projectList);

        referenceProjectTextBox.setColumns(20);
        referenceProjectTextBox.setRows(5);
        referenceProjectTextBox.setMinimumSize(new java.awt.Dimension(232, 92));
        jScrollPane2.setViewportView(referenceProjectTextBox);

        addReferenceProjectButton.setText("add reference project");
        addReferenceProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReferenceProjectButtonActionPerformed(evt);
            }
        });

        removeReferenceProjectButton.setText("remove reference project");
        removeReferenceProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeReferenceProjectButtonActionPerformed(evt);
            }
        });

        toProjectTreeButton.setText("add project");
        toProjectTreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toProjectTreeButtonActionPerformed(evt);
            }
        });

        addAnalysisGroupButton.setText("add a projectgroup");
        addAnalysisGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnalysisGroupButtonActionPerformed(evt);
            }
        });

        removeAnalysisGroupButton.setText("remove selected projectgroup");
        removeAnalysisGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAnalysisGroupButtonActionPerformed(evt);
            }
        });

        removeProjectButton.setText("remove project");
        removeProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProjectButtonActionPerformed(evt);
            }
        });

        projectTree.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        projectTree.setMinimumSize(new java.awt.Dimension(113, 19));
        jScrollPane3.setViewportView(projectTree);

        analyseButton.setText("proceed...");
        analyseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyseButtonActionPerformed(evt);
            }
        });

        fastaLocationTextField.setEditable(false);

        addFastaButton.setText("add fasta");
        addFastaButton.setEnabled(false);
        addFastaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFastaButtonActionPerformed(evt);
            }
        });

        ownFastaCheckBox.setText("use own fasta file");
        ownFastaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownFastaCheckBoxActionPerformed(evt);
            }
        });

        filterSubsetCheckBox.setText("only show subset of proteins");
        filterSubsetCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterSubsetCheckBoxActionPerformed(evt);
            }
        });

        accessionTextArea.setColumns(20);
        accessionTextArea.setRows(5);
        accessionTextArea.setText("list of accessions separated by enters");
        accessionScrollPane.setViewportView(accessionTextArea);

        filterCheckbox.setText("remove this subset instead");

        importSubsetButton.setText("import subset ...");

        saveSubsetButton.setText("save subset...");

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addComponent(accessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterCheckbox)
                    .addComponent(importSubsetButton)
                    .addComponent(saveSubsetButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addComponent(filterCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(importSubsetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveSubsetButton)))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(filterSubsetCheckBox, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(addReferenceProjectButton)
                                            .addComponent(removeReferenceProjectButton)
                                            .addComponent(addAnalysisGroupButton)
                                            .addComponent(toProjectTreeButton)
                                            .addComponent(removeAnalysisGroupButton)
                                            .addComponent(removeProjectButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ownFastaCheckBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fastaLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(addFastaButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(analyseButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addReferenceProjectButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(removeReferenceProjectButton))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(addAnalysisGroupButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(toProjectTreeButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(removeAnalysisGroupButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(removeProjectButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fastaLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addFastaButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ownFastaCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(analyseButton)))
                .addGap(16, 16, 16)
                .addComponent(filterSubsetCheckBox)
                .addGap(24, 24, 24)
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addReferenceProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReferenceProjectButtonActionPerformed
        if (projectList.getSelectedValue() != null) {
            referenceProject = (Experiment) projectList.getSelectedValue();
            referenceProjectTextBox.setText(referenceProject.getExperimentName());
        }
    }//GEN-LAST:event_addReferenceProjectButtonActionPerformed

    private void removeReferenceProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeReferenceProjectButtonActionPerformed
        if (!referenceProjectTextBox.getText().isEmpty()) {
            referenceProject = null;
            referenceProjectTextBox.setText("");
        }
    }//GEN-LAST:event_removeReferenceProjectButtonActionPerformed

    private void toProjectTreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toProjectTreeButtonActionPerformed
        if (!selectedProjectsList.contains((Experiment) projectList.getSelectedValue())) {
            DefaultMutableTreeNode projectNode = projectTree.addObject(projectList.getSelectedValue());
            projectNode.setAllowsChildren(false);
            selectedProjectsList.add((Experiment) projectList.getSelectedValue());
        }
    }//GEN-LAST:event_toProjectTreeButtonActionPerformed

    private void addAnalysisGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnalysisGroupButtonActionPerformed
        // TODO add your handling code here:
        String temp = JOptionPane.showInputDialog(null);
        if (temp != null) {
            if (!temp.isEmpty()) {
                projectTree.addObject(new AnalysisGroup(temp));
            }
        }
    }//GEN-LAST:event_addAnalysisGroupButtonActionPerformed

    private void removeAnalysisGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAnalysisGroupButtonActionPerformed
        if (projectTree.getSelectionPath() != null) {
            if (projectTree.getSelectionPath().getLastPathComponent() instanceof AnalysisGroup) {
                projectTree.removeCurrentNode();
            }
        }
    }//GEN-LAST:event_removeAnalysisGroupButtonActionPerformed

    private void removeProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProjectButtonActionPerformed
        // TODO add your handling code here:
        if (projectTree.getSelectionPath() != null) {
            if (projectTree.getSelectionPath().getLastPathComponent() instanceof Experiment) {
                selectedProjectsList.remove((Experiment) projectTree.getSelectionPath().getLastPathComponent());
                projectTree.removeCurrentNode();
            }
        }
    }//GEN-LAST:event_removeProjectButtonActionPerformed

    private void analyseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyseButtonActionPerformed

        boolean goAhead = false;
        //can we actually continue?
        List<AnalysisGroup<Experiment>> analysisList = new ArrayList<AnalysisGroup<Experiment>>();
        if (!selectedProjectsList.isEmpty() && referenceProject != null) {
            AnalysisGroup rogueProjects = new AnalysisGroup("Analysis");
            Enumeration tree = ((DefaultMutableTreeNode) projectTree.getModel().getRoot()).children();
            while (tree.hasMoreElements()) {
                Object anObject = tree.nextElement();
                if (((DefaultMutableTreeNode) anObject).getUserObject() instanceof Experiment) {
                    rogueProjects.add((Experiment) ((DefaultMutableTreeNode) anObject).getUserObject());
                } else if (((DefaultMutableTreeNode) anObject).getUserObject() instanceof AnalysisGroup) {
                    analysisList.add((AnalysisGroup) ((DefaultMutableTreeNode) anObject).getUserObject());
                }
                DataModeController.setDataSource(DataModeController.DataSource.DATABASE);
            }

            if (!rogueProjects.isEmpty()) {
                analysisList.add(rogueProjects);
            }
            goAhead = true;
            if (ownFastaCheckBox.isSelected() && fastaFile != null && goAhead) {
                //this sure as hell can be better
                DataModeController.setDb(DataModeController.Db.FASTA);
                ((FastaDataMode) DataModeController.getDb().getDataMode()).setFastaFile(fastaFile);
            } else if (ownFastaCheckBox.isSelected() && fastaFile == null) {
                goAhead = false;
            }
        }
        if (filterSubsetCheckBox.isSelected() && !accessionTextArea.getText().isEmpty()) {
            List<Protein> filterList = new ArrayList<Protein>();
            for (String accession : Arrays.asList(accessionTextArea.getText().split("\n"))) {
                filterList.add(new Protein(accession));
            }
            ((FastaDataMode) DataModeController.getDb().getDataMode()).getViewPreparationForMode().setProteinsToFilter(analysisList);
        }

        if (goAhead) {
            MainWindow window = new MainWindow(referenceProject, analysisList);
            faultBarrier.addObserver(window);
            window.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "please make sure you have a reference project, one or more projects to compare to and if requested, have supplied a fasta");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_analyseButtonActionPerformed

    private void addFastaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFastaButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fastaChooser = new JFileChooser();
        fastaChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fastaChooser.setMultiSelectionEnabled(false);
        fastaChooser.showOpenDialog(this);
        this.fastaFile = fastaChooser.getSelectedFile();
        if (fastaFile != null) {
            fastaLocationTextField.setText(fastaFile.getName());
            ViewProperties.getInstance().setProperty(new Property(ViewPropertyEnum.PROTEINFASTALOCATION, fastaFile.getAbsolutePath()));
        }
    }//GEN-LAST:event_addFastaButtonActionPerformed

    private void ownFastaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownFastaCheckBoxActionPerformed
        // TODO add your handling code here:

        if (ownFastaCheckBox.isSelected()) {
            addFastaButton.setEnabled(true);
            fastaFile = new File(ViewProperties.getInstance().getProperty(ViewPropertyEnum.PROTEINFASTALOCATION.getKey()));
            fastaLocationTextField.setText(fastaFile.getName());
        } else {
            addFastaButton.setEnabled(false);
        }
    }//GEN-LAST:event_ownFastaCheckBoxActionPerformed

    private void filterSubsetCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterSubsetCheckBoxActionPerformed
        // TODO add your handling code here:
        if (filterSubsetCheckBox.isSelected()) {
            filterPanel.setVisible(true);
            this.pack();
            this.repaint();
        } else {
            filterPanel.setVisible(false);
            this.pack();
            this.repaint();
        }

    }//GEN-LAST:event_filterSubsetCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane accessionScrollPane;
    private javax.swing.JTextArea accessionTextArea;
    private javax.swing.JButton addAnalysisGroupButton;
    private javax.swing.JButton addFastaButton;
    private javax.swing.JButton addReferenceProjectButton;
    private javax.swing.JButton analyseButton;
    private javax.swing.JTextField fastaLocationTextField;
    private javax.swing.JCheckBox filterCheckbox;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JCheckBox filterSubsetCheckBox;
    private javax.swing.JButton importSubsetButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox ownFastaCheckBox;
    private javax.swing.JList projectList;
    private com.compomics.pepshell.view.components.DragAndDropTree projectTree;
    private javax.swing.JTextArea referenceProjectTextBox;
    private javax.swing.JButton removeAnalysisGroupButton;
    private javax.swing.JButton removeProjectButton;
    private javax.swing.JButton removeReferenceProjectButton;
    private javax.swing.JButton saveSubsetButton;
    private javax.swing.JButton toProjectTreeButton;
    // End of variables declaration//GEN-END:variables

    public void update(Observable o, Object o1) {
        if (o1 != null) {
            if (o1 instanceof Exception) {
                faultBarrier.handleException((Exception) o1);
            }
        }
    }

    private void fillProjectList() throws SQLException {
        projectList.setListData(DbDAO.getProjects().toArray());
    }
}
