/*
 * Copyright 2014 Davy Maddelein.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.compomics.pepshellstandalone.dataloading;

import com.compomics.pepshell.model.AnnotatedFile;
import com.compomics.pepshell.model.SeparatedValueExperimentMetadata;
import com.compomics.pepshell.model.enums.PossibleMetaDataAnnotationsEnum;
import com.compomics.pepshellstandalone.ProgramVariables;
import com.compomics.pepshellstandalone.components.JFileChooserWithMemory;
import com.compomics.pepshellstandalone.exceptionhandling.ExceptionEvent;
import org.apache.logging.log4j.Level;

import java.awt.event.KeyEvent;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.LineNumberReader;
import java.time.Instant;
import java.util.Collections;
import java.util.List;
import java.awt.Cursor;
import java.util.Map;
import java.util.Properties;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * @author Davy Maddelein
 */
public class MetaDataProviderDialog extends javax.swing.JDialog {

    private final DefaultListModel<AnnotatedFile> model = new DefaultListModel<>();
    private AnnotatedFile reference;

    /**
     * Creates new form MetaDataProviderDialog
     */
    public MetaDataProviderDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    @Override
    public void setVisible(boolean visible) {
        extraMetaDataAnnotatorPanel1.clearMetaData();
        super.setVisible(visible);
    }

    public void setFilesToAnnotate(List<File> files) {
        model.clear();
        files.stream()
                .map((aFile) -> new AnnotatedFile(aFile.getAbsolutePath()))
                .forEach(model::addElement);
        filesToAnnotateList.setModel(model);
    }

    public void setFilesToAnnotate(File referenceFile, List<File> files) {
        model.clear();
        reference = new AnnotatedFile(referenceFile.getAbsolutePath());
        model.addElement(reference);
        files.stream()
                .forEach((aFile) -> model.addElement(new AnnotatedFile(aFile.getAbsolutePath())));
        filesToAnnotateList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        filesToAnnotateList = new javax.swing.JList<>();
        multipleExperimentsCheckbox = new javax.swing.JCheckBox();
        commitDataButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        extraMetaDataAnnotatorPanel1 = new com.compomics.pepshellstandalone.dataloading.ExtraMetaDataAnnotatorPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        SaveAnnotationsButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("provide meta data for experiment parsing");
        setPreferredSize(new java.awt.Dimension(920, 565));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setMinimumSize(new java.awt.Dimension(645, 455));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 460));

        jScrollPane2.setViewportView(filesToAnnotateList);

        multipleExperimentsCheckbox.setText("multiple experiments per file");
        multipleExperimentsCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleExperimentsCheckboxActionPerformed(evt);
            }
        });

        commitDataButton1.setText("confirm metadata addition");
        commitDataButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitDataButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(525, 80));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(525, 80));

        extraMetaDataAnnotatorPanel1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        extraMetaDataAnnotatorPanel1.setMinimumSize(new java.awt.Dimension(200, 80));
        extraMetaDataAnnotatorPanel1.setPreferredSize(new java.awt.Dimension(200, 80));
        extraMetaDataAnnotatorPanel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                extraMetaDataAnnotatorPanel1ComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                extraMetaDataAnnotatorPanel1ComponentRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(extraMetaDataAnnotatorPanel1);

        jButton1.setText("cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("load annotations");

        SaveAnnotationsButton.setText("save annotations");
        SaveAnnotationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAnnotationsButtonActionPerformed(evt);
            }
        });

        jButton2.setText("add metadata to selected experiments");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(SaveAnnotationsButton)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(commitDataButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multipleExperimentsCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(1285, 1285, 1285))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(multipleExperimentsCheckbox))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(SaveAnnotationsButton))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(commitDataButton1))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jMenu1.setText("Annotation Files");

        jMenuItem1.setText("save annotations");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("load annotations");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        SeparatedValueExperimentMetadata data = extraMetaDataAnnotatorPanel1.getAllAnnotations();
        JFileChooserWithMemory chooser = JFileChooserWithMemory.getInstance();
        chooser.setMultiSelectionEnabled(false);
        int state = chooser.showSaveDialog(this);
        if (state == JFileChooser.APPROVE_OPTION) {
            try {
                try (FileWriter writer = new FileWriter(chooser.getSelectedFile())) {
                    Properties properties = new Properties();
                    properties.putAll(data.getMetaDataAsMap());
                    properties.store(writer,"annotations written on "+ Instant.now());
                }
            } catch (IOException ex) {
                ProgramVariables.exceptionBus.post(new ExceptionEvent("could not write the annotations to file" ,true, Level.WARN));
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooserWithMemory chooser = JFileChooserWithMemory.getInstance();
        chooser.setMultiSelectionEnabled(false);
        int state = chooser.showOpenDialog(this);
        if (state == JFileChooser.APPROVE_OPTION) {

            this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));

            Properties annotations = new Properties();

            try (FileReader reader = new FileReader(chooser.getSelectedFile())){
                annotations.load(reader);
            } catch (IOException ioe) {
                ProgramVariables.exceptionBus.post(new ExceptionEvent("could not read the annotations from the file",true,Level.WARN));
            }

            if(annotations.isEmpty()){
                ProgramVariables.exceptionBus.post(new ExceptionEvent("no annotations found in file",true,Level.WARN));
            } else {
                annotations.entrySet().stream()
                        .forEach(e -> extraMetaDataAnnotatorPanel1.setAnnotation((String) e.getKey(), (String) e.getValue()));
            }

            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_A && evt.isControlDown()) {
            filesToAnnotateList.setSelectionInterval(0, filesToAnnotateList.getModel().getSize());
        }
    }//GEN-LAST:event_formKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void extraMetaDataAnnotatorPanel1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_extraMetaDataAnnotatorPanel1ComponentRemoved
        extraMetaDataAnnotatorPanel1.repaint();
        jScrollPane1.scrollRectToVisible(evt.getComponent().getBounds());
        this.pack();
    }//GEN-LAST:event_extraMetaDataAnnotatorPanel1ComponentRemoved

    private void extraMetaDataAnnotatorPanel1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_extraMetaDataAnnotatorPanel1ComponentAdded
        extraMetaDataAnnotatorPanel1.repaint();
        jScrollPane1.scrollRectToVisible(evt.getComponent().getBounds());
        this.pack();
    }//GEN-LAST:event_extraMetaDataAnnotatorPanel1ComponentAdded

    private void commitDataButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitDataButton1ActionPerformed
        
        StringBuilder builder = new StringBuilder("annotations added to files:\n");
        filesToAnnotateList.getSelectedValuesList().stream()
                .forEach(aFile -> builder.append(aFile.getName()).append("\n"));
        JOptionPane.showMessageDialog(this, builder.toString());
    }//GEN-LAST:event_commitDataButton1ActionPerformed

    private void multipleExperimentsCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleExperimentsCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multipleExperimentsCheckboxActionPerformed

    private void SaveAnnotationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAnnotationsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveAnnotationsButtonActionPerformed

    public AnnotatedFile getReferenceExperimentFile() {
        return reference;

    }

    public List<AnnotatedFile> getFiles() {

        return Collections.list(model.elements());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveAnnotationsButton;
    private javax.swing.JButton commitDataButton1;
    private com.compomics.pepshellstandalone.dataloading.ExtraMetaDataAnnotatorPanel extraMetaDataAnnotatorPanel1;
    private javax.swing.JList<AnnotatedFile> filesToAnnotateList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox multipleExperimentsCheckbox;
    // End of variables declaration//GEN-END:variables
}
